[auth]
redirect_uri = "https://pet-saude-sinais.streamlit.app/oauth2callback"
cookie_secret = "gere-uma-chave-aleatoria-com-pelo-menos-32-bytes"
client_id = "seu-client-id.apps.googleusercontent.com"
client_secret = "seu-client-secret"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
